<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $assessmentTitle }}</title>
    <style>
        /* PDF specific settings */
        @page { margin: 100px 50px; }
        
        * { box-sizing: border-box; }
        body { 
            font-family: 'Helvetica', 'Arial', sans-serif; 
            color: #333; 
            line-height: 1.6;
            margin: 0;
            padding: 0;
        }

        /* Top Header Section */
        .assessment-header {
            border-bottom: 2px solid #073a89;
            padding-bottom: 15px;
            margin-bottom: 30px;
        }
        
        h1 { 
            color: #073a89; 
            font-size: 24px; 
            margin: 0 0 8px 0;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        .meta-container {
            background: #f8fafc;
            padding: 12px 15px;
            border-radius: 6px;
            font-size: 13px;
            color: #64748b;
            display: table;
            width: 100%;
        }

        .meta-item {
            display: table-cell;
        }

        /* Question Blocks */
        .question-block { 
            margin-bottom: 30px; 
            padding: 5px 0;
            page-break-inside: avoid; /* Sawal ko page ke beech se tootne se bachata hai */
        }

        .question-header {
            margin-bottom: 12px;
        }

        .question-number { 
            font-size: 13px; 
            font-weight: 700;
            color: #94a3b8; 
            margin-bottom: 4px; 
            text-transform: uppercase;
        }

        .question-text { 
            font-size: 16px; 
            font-weight: 600; 
            color: #1e293b; 
            margin-bottom: 10px;
            line-height: 1.4;
        }

        .question-type { 
            display: inline-block; 
            font-size: 10px; 
            padding: 3px 12px; 
            border-radius: 4px; 
            background: #e0f2fe; 
            color: #0369a1; 
            font-weight: 700;
            text-transform: uppercase;
            margin-bottom: 15px;
        }

        /* Options Styling */
        .options-grid {
            margin-left: 5px;
        }

        .option { 
            font-size: 14px; 
            padding: 10px 15px; 
            background: #ffffff; 
            border: 1px solid #f1f5f9;
            border-radius: 6px; 
            margin-bottom: 8px; 
            color: #334155;
        }

        /* Footer */
        .footer { 
            position: fixed;
            bottom: -60px;
            left: 0;
            right: 0;
            height: 50px;
            font-size: 11px; 
            color: #94a3b8; 
            text-align: center; 
            border-top: 1px solid #e2e8f0; 
            padding-top: 15px; 
        }
    </style>
</head>
<body>
    
    <div class="assessment-header">
        <h1>{{ $assessmentTitle }}</h1>
        <div class="meta-container">
            <div class="meta-item"><strong>Course:</strong> {{ $courseName }}</div>
            <div class="meta-item" style="text-align: center;"><strong>Time:</strong> {{ $timeToComplete }} mins</div>
            <div class="meta-item" style="text-align: right;"><strong>Total Marks:</strong> {{ $totalMarks }}</div>
        </div>
    </div>

    @foreach($questions as $index => $question)
        <div class="question-block">
            <div class="question-header">
                <div class="question-number">Question {{ $index + 1 }}</div>
                <div class="question-text">{{ $question->question }}</div>
                <span class="question-type">{{ $question->assessment_type }}</span>
            </div>

            @if($question->options)
                <div class="options-grid">
                    @foreach($question->options as $optIndex => $option)
                        <div class="option">
                            <strong style="color: #94a3b8; margin-right: 10px;">{{ chr(65 + $optIndex) }}.</strong> {{ $option }}
                        </div>
                    @endforeach
                </div>
            @endif
        </div>
    @endforeach

    <div class="footer">
        Generated by DotBitz Learning Platform &nbsp;|&nbsp; &copy; {{ date('Y') }} All rights reserved.
    </div>

</body>
</html>